In [1]:
print("Hello Sunny!!!")

Hello Sunny!!!


In [2]:
x=10
print(x)

10


In [3]:
x=10
if x==10:
    print("true")
else:
    print("false")

true


In [4]:
a=5


In [5]:
print(a)

5


In [6]:
a=6

In [7]:
print?

In [8]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [9]:
# comments

# comments

In [10]:
'''
multi 
line
comment
'''

'\nmulti \nline\ncomment\n'

In [11]:
import math
print(math.factorial(10))


3628800


In [ ]:
name = input()
prin

In [ ]:
numbers = input("enter numbers")
print(numbers)
print(type(numbers))


In [ ]:
#numbers = input("enter numbers")
#print(numbers)
#print(type(numbers))
#numbers="1 2 3 4 5"



In [ ]:
list_numbers="1 2 3 4 5"
print(list_numbers)

In [5]:
a='abhisghsv'
b='hvgsv'
 

In [7]:
print(a[3])

i


In [8]:
string='ssr'

In [9]:
string


'ssr'

In [10]:
del string

In [11]:
string

NameError: name 'string' is not defined

In [12]:
a='this is the  python session at AI mafia'

In [18]:
a.find('python')
a.find('at')
sliced=a[13:27:2]

In [19]:
print(sliced)

pto eso


In [26]:
a='coding club'
sliced=a[::-1]
print(sliced)

gnidoc


In [22]:
print(sliced)

In [30]:
if 'ing' in a:
    print('present')

present


In [31]:
a.lower()

'coding'

In [32]:
a.upper()

'CODING'

In [33]:
a.title()

'Coding'

In [34]:
a.capitalize()

'Coding'

In [35]:
len(a)

6

In [39]:
a.find('cool')

-1

In [40]:
a.index('co ol')

ValueError: substring not found

In [41]:
def check(str,sub):
    if str.find(sub)==-1:
        print('not found')
    else:
        print('found')

In [43]:
check('ssreddy','cool')

not found


In [44]:
a.upper()

'CODING'

In [47]:
a.casefold()

'coding'

In [48]:
a.casefold()

'coding'

In [52]:
a.center(663)

'                                                                                                                                                                                                                                                                                                                                         coding                                                                                                                                                                                                                                                                                                                                        '

# LIST

In [55]:
l=['mango','apple','banana']
print(l)

['mango', 'apple', 'banana']


In [56]:
print(l,type(l))

['mango', 'apple', 'banana'] <class 'list'>


In [58]:
l2=[1,2,3,4]
l.append(l2)
print(l)

['mango', 'apple', 'banana', [1, 2, 3, 4], [1, 2, 3, 4]]


In [64]:
l2.insert(1,'orange')
print(l2)


[1, 'orange', 'orange', 'orange', 2, 'orange', 'orange', 3, 4]


In [68]:
l2.remove('orange')
print(l2)

[1, 'orange', 'orange', 'orange', 'orange', 3, 4]


In [69]:
l2.pop()

4

In [70]:
l2.pop()

3

In [71]:
l2.pop()

'orange'

In [72]:
l2.pop()

'orange'

In [73]:
l2


[1, 'orange', 'orange']

In [74]:
l2[::-1]
print(l2)

[1, 'orange', 'orange']


In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [3]:
arr= np.array([[1,2,3],
               [4,2,5]])

In [4]:
 type(arr)

numpy.ndarray

In [5]:
arr.ndim

2

In [8]:
arr.shape

(2, 3)

In [9]:
arr.size

6

In [10]:
c=np.zeros((3,4))


In [11]:
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.eye?

In [15]:
np.arrange(0,30,5)

AttributeError: module 'numpy' has no attribute 'arrange'